### ISSUE TITLE
Text clipping in buttons

### ISSUE THREAD

**Issue by vinsworldcom** [molsonkiko/JsonToolsNppPlugin#12]
I suspect there is some text clipping in the buttons in the UI:

![image](https://user-images.githubusercontent.com/9657169/191977452-2805b26c-235b-4b85-8420-2ed0ee841839.png)

Assuming top right should be "Query to CSV" - notice the "V" is clipped
Assuming bottom left should be "Current Path" - notice the "h" is clipped.

To be honest, not sure the bottom left button is even needed as you can highlight the text and either `CTRL+C` or right click in the and select copy from the menu.

Cheers.

**Comment by vinsworldcom** [comment]
Also note, the checkbox overlaps with the query text box.

**Comment by molsonkiko** [comment]
I tried to fix this issue in my last commit, but since I never saw the issues on my own computer, only someone who previously saw them can tell me if they're gone. Sorry it took me so long to get around to this.

@vinsworldcom , when you submitted that issue about the URLs box in the `JSON from files and APIs` form, I noticed some more similar text clipping in the title and one of the labels. I'd really appreciate if you could look at my other forms (find/replace, JSON->CSV, `JSON from files and APIs`) and let me know if there's still any clipping there.

**Comment by vinsworldcom** [comment]
Looks better:

![image](https://user-images.githubusercontent.com/9657169/227402906-de1d8fb9-8465-4128-807b-aae503181361.png)

Notice some still misalignment, but no clipped text in buttons:
![image](https://user-images.githubusercontent.com/9657169/227402988-35ad2573-1c42-4ad6-9dc5-c4aca0fdbb60.png)

![image](https://user-images.githubusercontent.com/9657169/227403158-c3118b79-aa93-4030-bfa5-9b78eb49ddcd.png)


Cheers.

**Comment by molsonkiko** [comment]
Should be better now.
