### ISSUE TITLE
Could not parse the document because of error Key in object (would be Key 5) must be string at position 1024 (char '*')

### ISSUE THREAD

**Issue by zhchaoxing** [molsonkiko/JsonToolsNppPlugin#26]
First time use this tool. Cannot use any of the features after installing. 
version 4.0.0.1
Pops error: Could not parse the document because of error Key in object (would be Key 5) must be string at position 1024 (char '*')

**Comment by molsonkiko** [comment]
Hi @zhchaoxing , thanks for letting me know about this issue. Can you share debug info (`?->Debug Info...` from the main menu) and the text of the document that caused the issue so I can better understand the problem?

I recommend that you first try installing a newer version of JsonTools. I've made substantial improvements since 4.0.0.1.

**Comment by zhchaoxing** [comment]
Hi @molsonkiko Thanks for getting back to me so quickly, I just realized that in the massy json (which is why I needed this plugin) there's a line from curl inserted "* Connection #0 to host left intact" in the middle, causing the problem. False alarm.
Although I do hope the error info is more direct, instead of saying "error Key in object (would be Key 5) must be string at position 1024 (char '*')". 
I am installing the plugin from the Plugin Admin and 4.0.0.1 is the latest there.
Thanks!
