### ISSUE TITLE
When I choose to move a tab to "Other View", plugin does not run.

### ISSUE THREAD

**Issue by ahazelwood** [molsonkiko/JsonToolsNppPlugin#31]
I opened a new tab in Notepad++ 8.5 and pasted in some json content.  If I Pretty Print the content, it works fine.  If I then move the tab to another view by right clicking on the tab and select "Move to Other View", the plugin will not run in the same document with different content on the Other View.  It will work fine on the original view.

Thanks.

**Comment by molsonkiko** [comment]
I'm not sure what you mean exactly. First of all, which version of JsonTools are you using? Any version before 4.9.1 does not correctly work with multiple instances or views open. So you should probably upgrade to a newer version in that case (4.11.1 is the latest).

If you are using 4.9.1 or later, I don't know what you mean and I need some clarification. Since this is a UI problem, an image would be nice.

I assume what you're talking about is this:
![multi-instance with tree view](https://user-images.githubusercontent.com/46202915/225994507-cddef4e6-3862-432a-8734-3fe5aa1b878c.png)
and you want to be able to do plugin actions on the saved query result.

On my computer, this setup works fine on the most recent version, 4.11.1.

**Comment by ahazelwood** [comment]
I believe that is what was going up.  There was an update to v4.10 and it is working as expected.

Thanks.
