### ISSUE TITLE
[feature request] Save JSON API paths

### ISSUE THREAD

**Issue by vinsworldcom** [molsonkiko/JsonToolsNppPlugin#32]
In the "JSON from file and APIs" form, it would be nice to remember - say the last 10 - "Get JSON from APIs" entries and have them auto-populated when the form opens.

![image](https://user-images.githubusercontent.com/9657169/226054926-18b5684e-a998-4d46-885b-c0147c495ad8.png)

I realize just populating that window would mean fetching them all (again) when pressing the "Send requests" button.  I think it would be relatively easy to store in the config file up to 5 or 10 most-recently-used URLs.  Just how to make them accessible in this window for each recall?

Cheers.

**Comment by molsonkiko** [comment]
Good idea! Probably a good way to do it is to store "sessions" (probably implemented as a JSON config file mapping session names to arrays of URLs).
Since you're the first person to ask for anything related to the grepper form, I'd be curious if you can think of any other improvements I could make.

**Comment by molsonkiko** [comment]
The [most recent commit](https://github.com/molsonkiko/JsonToolsNppPlugin/commit/db0d96fae0f58e9249a618213d634e2ab6b29765) implements this.

**Comment by molsonkiko** [comment]
I'd say the new implementation is a minimum viable product. I don't get the impression that this form is very widely used, and if someone is really unhappy with having to delete the URLs that auto-populate the field (unreasonable IMO because they can just Ctrl+A and then backspace), I might re-implement it in some other way. I'm open to suggestions.
