### ISSUE TITLE
Support Using '#' for Commenting

### ISSUE THREAD

**Issue by mtlive** [molsonkiko/JsonToolsNppPlugin#33]
Some programs use # as line commenting character, and trying to pretty print such JSON files with this plugin raises a parsing error.
May you add it to the commenting characters?

**Comment by molsonkiko** [comment]
Nobody *should* do this. JSON stands for __JavaScript__ Object Notation, and the [JSONC](https://code.visualstudio.com/docs/languages/json#_json-with-comments) and [JSON5](https://json5.org/) standards only support JavaScript comments.

If you can get those people to stop doing this, you really should, because they're just abusing the JSON standard in a particularly irritating way.

With that said, this was a pretty easy fix and it didn't meaningfully degrade parsing performance, so here you go.

**Comment by mtlive** [comment]
> If you can get those people to stop doing this, you really should, because they're just abusing the JSON standard in a particularly irritating way.

Noted down. Thank you for pointing this out.
