### ISSUE TITLE
[Feature Request] Use tabs instead of spaces when pretty printing

### ISSUE THREAD

**Issue by Kiryonn** [molsonkiko/JsonToolsNppPlugin#38]
As in the title, adding the possibility to choose between spaces and tabs.

**Comment by molsonkiko** [comment]
I may consider doing this in the future. It's not a high priority because (a) adding a new special case to my pretty-printing functions would increase code bloat and impair performance, (b) all the usual reasons that people object to using tabs for indentation, and (c) if you care about saving space when printing JSON, you should just compress it.

Suppose you want to indent with tabs, and you have `n` spaces for indentation.
Use the find/replace form (regular expression __ON__). Find/replace `(?:^|(?!\A)\G)\t*\K\x20{n}` with `\t` to convert all leading sequences of `n` spaces to tabs.

**Comment by Kiryonn** [comment]
I already replace 4 spaces with tab using Ctr+h, which isn't that hard nor a pain to deal with tbh. It's just that i'm lazy and like tabs better since you can get better space management while having a readable code.
I do agree that for using json in a code I'd rather just compress it.

**Comment by molsonkiko** [comment]
Closed by [latest commit](https://github.com/molsonkiko/JsonToolsNppPlugin/commit/0d138f5c9f535d4cd33a0a0b69fe5ccf201e192b).
