### ISSUE TITLE
Pretty-print: Unicode characters are converted to their unicode

### ISSUE THREAD

**Issue by ghbm-itk** [molsonkiko/JsonToolsNppPlugin#41]
When doing 'Pretty-print current JSON file' some unicode characters are converted to their unicode.
Example:
"Indledning - præklusivt proklama" ->"Indledning - pr\u00e6klusivt proklama"

Windows 10
JSON Tools v4.0.0.1
Notepad++ v8.4.7 (64 bits)
Encoding UTF-8

**Comment by molsonkiko** [comment]
Fixed in more recent versions, the earliest being [4.7.0](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/CHANGELOG.md#470---2022-12-20), although I recommend downloading the [latest](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v5.3.0), unzipping the x64 or x86 binary depending on whether you have a 64bit or 32bit Notepad++ installation, and replacing the contents of your `Notepad++/plugins/JsonTools` folder with the contents of the folder that you unzipped.

**Comment by ghbm-itk** [comment]
The new update to json tools weren't showing up because my notepad wasn't up to date. It works perfectly now, thanks!
