### ISSUE TITLE
Open JSON tree viewer stays checked in plugin menu

### ISSUE THREAD

**Issue by SuperDre** [molsonkiko/JsonToolsNppPlugin#50]
When you add a new tab to notepad and paste some json into it, and you select the 'Open JSON tree viewer' through the plugin menu, the document shifts to JSON and the tree viewer is visible on the right. When you open the plugin menu you'll see a big checkbox in front of the option. If you select the option again, the tree viewer on the left disapears, but when you open the plugin menu you'll see that the option still has the checkbox in front of it.

**Comment by molsonkiko** [comment]
This is due to an implementation quirk of the JSON tree, which I have no intention of changing.
Furthermore, you can actually have multiple JSON trees open (although only one can be seen at a time), and what would you expect the state of the button to be if you close one tree but others are open?

For these reasons and the additional reason that the toolbar is a Notepad++ component that I don't really understand or care to learn much more about, I have no intention of fixing this issue. Sorry.
