### ISSUE TITLE
How to increase the plugin "Tree View" font size?

### ISSUE THREAD

**Issue by PeterCodar** [molsonkiko/JsonToolsNppPlugin#66]
Currently, the Notepad++ plugin appears in a really tiny font in my environment:

![image](https://github.com/molsonkiko/JsonToolsNppPlugin/assets/18629146/957f0267-4fd7-4ab9-b22e-ae6ef4860dbe)

How can I increase the font size to make it easier to read the JSON details in the “Json Tree View” on the left-hand side?

**Comment by molsonkiko** [comment]
@PeterCodar 

That seems like a reasonable request. I'm going to try to work on it today.

Do you think the font for any other forms (or fields of forms) in JsonTools should be configurable, or just the font size for the tree view?

**Comment by Grisgram** [comment]
Hi,

I would also really love to see a config for the font, and while you're working on that part:

* When Notepad++ is in dark mode, your icons in the treeview still have a bright white background which is quite an eye-killer. can you make the `{}` icons of the tree transparent please?

**Comment by PeterCodar** [comment]
@molsonkiko 
Sorry for my late reply. For some unknown reason, I did not receive a notification for your comment.

Where can I find your "probably fixed version" to test it?

The font size for the tree view would be my most important wish, but If you can adjust the forms too, it would be of course appreciated too.

**Comment by molsonkiko** [comment]
@PeterCodar
> Where can I find your "probably fixed version" to test it?
I made a commit about three weeks ago, but I never got around to making an official release that incorporated the change. I'm going to try to make a new release within the next week that incorporates the change. Sorry for the delay!

@Grisgram 
> can you make the {} icons of the tree transparent please?

I can't make the icons "transparent", because the background of the icons is part of the image files that the icons are derived from.

What I *can* do is create dark mode icons, use dark mode icons when the Notepad++ background is "very dark" and the old "light mode" icons the rest of the time.

Below is an image of the new dark mode icons in the "Vim Dark Blue" Notepad++ theme. You will notice that the icon background is *not exactly the same as the tree background* (because, again, this is impossible), but it is dark and so the icons look less out of place.

![image](https://github.com/molsonkiko/JsonToolsNppPlugin/assets/46202915/ecb98f7c-4eb2-4b35-8d5d-109b5d0f4f18)

I have also tested the dark mode icons on the normal background for Notepad++ dark mode; the background blends in *seamlessly*.

**Comment by molsonkiko** [comment]
This feature is added in [JsonTools v8, the most recent release](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.0).

**Comment by Grisgram** [comment]
Thank you! 
When will it be available through the regular Plugins-Admin channel?

**Comment by molsonkiko** [comment]
JsonTools v8 is in the most recent version of the plugin list, which will ship with Notepad++ 8.6.9, which should be download-able in a week or so.
