### ISSUE TITLE
Weird Decimal Conversion Issue

### ISSUE THREAD

**Issue by KeanuTang** [molsonkiko/JsonToolsNppPlugin#81]
Here's a simple scenario. I have the following Json:

{"Amount": 11.11}
![image](https://github.com/user-attachments/assets/6365227d-7c70-4174-bf9f-a34b12a0f960)

When I run "Pretty-print current JSON file", the number changes from 11.11 to 11.109999999999999.

![image](https://github.com/user-attachments/assets/0d2be248-8314-4df1-9c6e-bdf6a9cc941f)

**Comment by molsonkiko** [comment]
This is not a bug *per se*, but rather an unfortunate consequence of my fix to #78.

Since loss of precision (that issue) means __unrecoverable and unnecessary__ loss of information, whereas your issue is merely an unnecessarily ugly string representation of a number, I will leave this unfixed.

If you're confused, I recommend that you Google "floating point imprecision" to help you understand why some imprecision is unavoidable.

**Comment by KeanuTang** [comment]
It seems fundamentally wrong that a plugin that is supposed to "pretty print" Json ends up manipulating the json data. That means that I can't use and trust your plugin's output because this is absolutely not just an "ugly string representation." 11..11 and 11.1099999xxx are completely different numbers, and "close enough" does not work in the real world of business and science.

**Comment by molsonkiko** [comment]
@KeanuTang 

I recommend that you stop wasting your breath chiding me for this issue. I will not fix it myself, because as I already explained I don't believe that the alternative solutions are acceptable or feasible to implement, as they involve (a) massive refactoring and loss of performance to pivot from double-precision floating point numbers to decimal numbers, (b) loss of precision when pretty-printing other numbers and thus a regression on #78, or (c) implementing my own (undoubtedly bug-ridden) algorithm that somehow fixes your issue while still using doubles. 

You are welcome to submit a PR that would fix this issue, but don't be surprised if I reject it because I don't like the tradeoffs you made.

There are other JSON plugins you can try if you don't like this one. There is a strong likelihood that they will have the same issue that mine does, because almost everyone uses double-precision floating point number to represent real numbers because, again, the alternative solutions are much harder to use and less performant.

**Comment by molsonkiko** [comment]
The reason I said this is not a bug in my original commend is that 11.11 is not "close enough" to 11.109999999999999 as far as double-precision floating point numbers are concerned; it is __equal.__ By contrast, the earlier algorithm I was using was changing the string representation in a way that would be parsed to a non-equal double. [Decimals](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-decimal) are not a reasonable substitute because the maximum value for a decimal is far less (7.9e28) than the maximum value for a double (1.8e308).

Any alternative with no rounding errors for any number of reasonable size would require me to fish for some third-party library that provides a higher-precision numeric specification while still having comparable performance and memory usage to doubles and an equally generous range of acceptable values, and then tediously change every `double` parameter, return type, and variable initialization in the entire plugin to the different type.

**Comment by molsonkiko** [comment]
@KeanuTang

I hope that JSON Viewer meets your needs, and I'm sorry if I came across as a jerk. But be warned; that plugin also uses doubles to represent real numbers, and I have no idea how their double-to-decimal and decimal-to-double algorithms compare to the one I'm using. They may be strictly better, or it may just make a different set of tradeoffs than the one I'm using. Regardless, since they use the same data type, they are subject to the same fundamental limitations as my plugin.

The only thing I know for sure is that if I try to implement these conversion algorithms myself, I will almost certainly do a worse job than the standard library and introduce many subtle bugs. If you think you can do a better job than the C# standard library, or point me to a library that you are extremely confident does better than the standard library, I would consider a fix.

**Comment by molsonkiko** [comment]
@KeanuTang 

[This commit](https://github.com/molsonkiko/JsonToolsNppPlugin/commit/f259bf6f6a16f53a477390670e0a1776b60e7db5) should address this issue. If you follow [my instructions for downloading an unreleased version](https://github.com/molsonkiko/JsonToolsNppPlugin?tab=readme-ov-file#downloading-unreleased-versions), you can test out this fix and see if it is too your liking.

As I noted in the changelog, this fix comes at the cost of noticeably worse performance when reformatting very large files (say, several megabytes or more). At some point I will see if I can implement a more performant solution.

Please let me know if you have any thoughts. If you are satisfied with this fix, I will be including it in v8.2 of JsonTools, which I aim to release in the next few weeks.

I must extend my sincerest apology to you for effectively gaslighting you and trying to trivialize what was in fact a real and substantial issue with my plugin.

**Comment by molsonkiko** [comment]
[JsonTools version 8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2), incorporating a fix for this issue, is now live. I will soon submit a PR to include v8.2 in the plugins manager.
