### ISSUE TITLE
New JSON Tools settings make it very difficult to use

### ISSUE THREAD

**Issue by 00155837364765867** [molsonkiko/JsonToolsNppPlugin#87]
Hi,
I've always really liked this plugin, as it can be used for linting, formatting, compressing, viewing etc.
But the newer versions have changed the settings (default settings?) whereby it's really tricky to use now.

If using this for linting, by default settings means it just deletes stuff it doesn't like (json format errors).
I wouldn't have thought there would be anyone using this plugin that would want that!
Used to show where the error was, so it could be edited and fixed.

Also now the new default seems to be to sort the keys. JSON isn't primarly meant for human reading.
There are certainly times where sorting keys could be handy, but this should be a separate shortcut key (more of an edge case e.g sorting a long array list of labels).
Auto-sorting when doing data structures often (usually?) makes the json *less* readable (e.g. putting a "meta" object in the middle instead of at the top where it was originally placed).

Thank you for making/maintaining this excellent plugin. If the defaults can be made less 'heavy handed' that would be awesome!.

**Comment by molsonkiko** [comment]
@00155837364765867 

> Also now the new default seems to be to sort the keys.

You are not using [the most recent version of JsonTools](https://github.com/molsonkiko/JsonToolsNppPlugin/releases). JsonTools has had that setting off by default since v7. Rather than address your complaints one by one, I would suggest that you upgrade to [v8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2) and see whether you are satisfied.

> If using this for linting, by default settings means it just deletes stuff it doesn't like (json format errors).

More recent versions of JsonTools have an [error form](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/docs/README.md#error-form-and-status-bar) and a [`Check JSON syntax now` command](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/docs/README.md#check-json-syntax-now) that refreshes the error form and shows any errors that were found without reformatting the file.

**Comment by molsonkiko** [comment]
@00155837364765867 

Since you have given me no reason to believe that you have any issues that haven't been fixed in my most recent release of JsonTools, I'm closing this issue. If you have an issue that's not related to the ones you described in your initial comment, you should probably open a new issue (or comment on an existing issue if yours is related), rather than commenting on this issue.

**Comment by molsonkiko** [comment]
[This documentation,](https://npp-user-manual.org/docs/plugins/#install-plugin-manually) should help you install a newer JsonTools release manually. I recommend [v8.3.1](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.3.1).
