### ISSUE TITLE
Reformatting is escaping unicode characters

### ISSUE THREAD

**Issue by lukaszwitko** [molsonkiko/JsonToolsNppPlugin#88]
Simple test:
`{"test":"... Lorém Ipsum’s ..."}`
is  pretty prinnted as
`{
  "test": "... Lor\u00e9m Ipsum\u2019s ..."
}`

Would it be possible to add a toggle in settings to escape them?

**Comment by molsonkiko** [comment]
You are using an ancient version of JsonTools. All non-ASCII unicode characters have been unescaped since v4.7. Update to [JsonTools v8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2) (the latest version) by downloading the appropriate version (64-bit or 32-bit) of that release and installing it by [following these instructions](https://npp-user-manual.org/docs/plugins/#install-plugin-manually).

As for adding a toggle in settings to allow non-ASCII characters to be unescaped (i.e., allowing the old behavior in addition to the current behavior), I have no intention of doing that because it would be too annoying to add for (IMO) too little gain.
